on:
  push:
    branches:
    - main
    - overleaf
  workflow_dispatch:
    
jobs:
  latex:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - name: GitHub Action for LaTeX
      uses: hspaans/latexmk-action@v2.1.0
      with:
          format: pdf
          filename: Final-Project-main.tex
          options: -shell-escape -bibtex -lualatex -verbose
    - name: Upload compile artifacts
      if: failure()
      uses: actions/upload-artifact@v6
      with:
        name: LaTeX Log
        path: Final-Project-main.log
    - name: Upload PDF
      uses: actions/upload-artifact@v6
      with:
        name: Compiled PDF
        path: Final-Project-main.pdf
        
