on:
  push:
    branches:
    - main
    - overleaf
  workflow_dispatch:
    
jobs:
  latex:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - name: GitHub Action for LaTeX
      uses: xu-cheng/latex-action@4.0.0
      with:
        root_file: Final-Project-main.tex
        texlive_version: 2025
        extra_system_packages: "inkscape ghostscript"
        latexmk_use_lualatex: true
        latexmk_shell_escape: true
    - name: Upload PDF file
      uses: actions/upload-artifact@v6
      with:
        name: Artifacts
        path: |
          Final-Project-main.pdf
          Final-Project-main.log
        
